permalink: /posts/:title
markdown: kramdown
# pygments: true
path: http://heyitsgarrett.com
title: Hey it's Garrett!
collections:
  sketchbook:
    output: true
    permalink: /sketchbook/index.html
  photography:
    output: true
    permalink: /photography/index.html
